WeatherForecast metorology1 = new WeatherForecast("Tarim",35,25,27);
metorology1.GetWeatherForecast();
WeatherForecast metorology2 = new WeatherForecast("Seyioun",25,5,27);
metorology2.GetWeatherForecast();
WeatherForecast metorology3 = new WeatherForecast("Almukala",35,15,27);
metorology3.GetWeatherForecast();
WeatherForecast metorology4 = new WeatherForecast("Istanbul",-1,25,27);
metorology4.GetWeatherForecast();
WeatherForecast metorology5= new WeatherForecast("Samsun",5,5,27);
metorology5.GetWeatherForecast();
WeatherForecast metorology6= new WeatherForecast("Cairo",5,15,27);
metorology6.GetWeatherForecast();